//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_viaje
    {
        public int estado_viaje1 { get; set; }
        public Nullable<int> codigo_tras { get; set; }
    
        public virtual traslado traslado { get; set; }
    }
}
