//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int num_factura { get; set; }
        public int codigo_viaje { get; set; }
        public int cliente { get; set; }
        public int id_moto { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string estado_pago { get; set; }
    
        public virtual traslado traslado { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario_moto usuario_moto { get; set; }
    }
}
