//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int num_factura { get; set; }
        public int codigo_viaje { get; set; }
        public int cliente { get; set; }
        public int id_moto { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string estado_pago { get; set; }
    
        public virtual Traslado Traslado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario_Moto Usuario_Moto { get; set; }
    }
}
