//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTO
    {
        public string modelo { get; set; }
        public string Registro { get; set; }
        public string Patente { get; set; }
        public string Seguro { get; set; }
        public byte[] Foto { get; set; }
    }
}
