//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moto
    {
        public int patente { get; set; }
        public int usuario_id { get; set; }
        public string modelo { get; set; }
        public string registro { get; set; }
        public string seguro { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
