//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MotoDeliveryEntities1 : DbContext
    {
        public MotoDeliveryEntities1()
            : base("name=MotoDeliveryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estado_viaje> estado_viaje { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<moto> motoes { get; set; }
        public virtual DbSet<traslado> trasladoes { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<usuario_moto> usuario_moto { get; set; }
    }
}
