//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int Codigo_viaje { get; set; }
        public string Met_Pago { get; set; }
        public string Estado_pago { get; set; }
        public string importe { get; set; }
        public string Numero_Factura { get; set; }
    }
}
