//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuario
    {
        public int Codigo_id { get; set; }
        public int Tipo_Usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
