//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class traslado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public traslado()
        {
            this.estado_viaje = new HashSet<estado_viaje>();
            this.facturas = new HashSet<factura>();
        }
    
        public int codigo_tras { get; set; }
        public int usuario_id { get; set; }
        public int id_moto { get; set; }
        public string tarifa { get; set; }
        public string calle_in { get; set; }
        public string altura_in { get; set; }
        public string piso_in { get; set; }
        public string dep_in { get; set; }
        public string calle_fn { get; set; }
        public string altura_fn { get; set; }
        public string piso_fn { get; set; }
        public string dep_fn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estado_viaje> estado_viaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> facturas { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario_moto usuario_moto { get; set; }
    }
}
