//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Traslado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Traslado()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int codigo_tras { get; set; }
        [Required]
        [Display(Name = "Elija su Usuario ID")]
        public int usuario_id { get; set; }
        [Display(Name = "No seleccionar")]
        public Nullable<int> id_moto { get; set; }
        [Required]
        [Display(Name = "Ingrese Tarifa Aproximada")]
        public string tarifa { get; set; }
        [Required]
        [Display(Name = "Ingrese Calle de Origen")]
        public string calle_in { get; set; }
        [Required]
        [Display(Name = "Ingrese Calle Destino")]
        public string calle_fn { get; set; }
        [Required]
        [Display(Name = "Ingrese Estado del Viaje")]
        public int estado_viaje { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario_Moto Usuario_Moto { get; set; }
    }
}
