//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Codigo_id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string doc_type { get; set; }
        public string num_doc { get; set; }
        public string pais { get; set; }
        public System.DateTime f_nacimiento { get; set; }
        public string calle { get; set; }
        public string altura { get; set; }
        public string piso { get; set; }
        public string departamento { get; set; }
        public string cp { get; set; }
    }
}
