//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public viaje()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int Id_Usuario_Pide { get; set; }
        public int Id_Usuario_Realiza { get; set; }
        public int Codigo_viaje { get; set; }
        public string Calle_in { get; set; }
        public string Altura_in { get; set; }
        public string Piso_in { get; set; }
        public string dep_in { get; set; }
        public string Calle_fn { get; set; }
        public string Altura_fn { get; set; }
        public string Piso_fn { get; set; }
        public string dep_fn { get; set; }
    
        public virtual pago pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
