//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traslado
    {
        public int codigo_tras { get; set; }
        public string id_usuario { get; set; }
        public string id_moto { get; set; }
        public string tarifa { get; set; }
        public string calle_in { get; set; }
        public string calle_fn { get; set; }
        public int estado_viaje { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Moto Moto { get; set; }
    }
}
