//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traslado
    {
        public int codigo_tras { get; set; }
        public string id_usuario { get; set; }
        public string id_moto { get; set; }
        public string tarifa { get; set; }
        public string calle_in { get; set; }
        public string calle_fn { get; set; }
        public int estado_viaje { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Moto Moto { get; set; }
    }
}
