//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Datos
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Threading.Tasks;
    using Microsoft.AspNet.Identity;
    using Microsoft.Owin.Security;

    public partial class UserData
    {
        [Required]
        [Display(Name = "Id Usuario")]
        public string Id_Usuario { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Required]
        [Display(Name = "Apellido")]
        public string apellido { get; set; }
        [Required]
        [Display(Name = "País")]
        public string pais { get; set; }
        [Required]
        [Display(Name = "Tipo de Documento")]
        public string doc_tipo { get; set; }

        internal static Task<object> FindAsync(string id)
        {
            throw new NotImplementedException();
        }

        [Required]
        [Display(Name = "Número de Documento")]
        public string num_doc { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha de Nacimiento")]
        public System.DateTime f_nac { get; set; }
        [Required]
        [Display(Name = "Calle")]
        public string calle { get; set; }
        [Required]
        [Display(Name = "Altura")]
        public string altura { get; set; }
        [Required]
        [Display(Name = "Departamento")]
        public string dep { get; set; }        
        public Nullable<bool> UsuarioNuevo { get; set; }    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
